### ISSUE TITLE
Tags not being saved

### ISSUE THREAD

**Issue by nathanl** [kkuchta/Vimbits#10]
I've contributed several vimbits and entered tags for them, but the tags were not saved. I've tried editing to fix that, but they're still not saved.

I've tried this in Chrome and Firefox, both on OSX.

**Comment by kkuchta** [comment]
Can you verify that after each tag, you'r hitting enter?  Done correctly, it should look like this:

http://i.imgur.com/8JQSV.png

Definitely some seriously usability issues there that I need to work out, but that's the default for the js library I used, and I haven't had time to fix it yet.

**Comment by nathanl** [comment]
Nope, that was it. :) Apparently I was the user who didn't notice your instruction to "hit enter to add tag". I was expecting it to work like StackOverflow's tags, but I should have read the directions.

Thanks!

**Comment by kkuchta** [comment]
Glad that fixed it.  Definitely need to make that more intuitive.  :)
