### ISSUE TITLE
Unnecessary  [...] on snippets list

### ISSUE THREAD

**Issue by uolot** [kkuchta/Vimbits#12]
When I paste a snippet which has a blank line at the end that line is displayed as `[...]` on snipets list.

**Comment by kkuchta** [comment]
Hmmm... I'll take a look at it.  The [...] appears when there's more than 5 lines or 1000 characters.  Can you paste in the snippet you entered?

**Comment by uolot** [comment]
I created two different two-liners and it happens to both of them. This one for example:

``` vim
nnoremap <silent> ss :split<CR>
nnoremap <silent> vv :vsplit<CR>

```

Empty line (3rd) is important. I think stripping top and bottom empty lines should do the job.

**Comment by adamransom** [comment]
I wasn't sure how to attach code to this issue, so I have submitted a separate pull request with a fix for this.

**Comment by kkuchta** [comment]
Thanks for the fix, Adamrandom!

**Comment by adamransom** [comment]
No worries, and you almost got my name right ;)
