### ISSUE TITLE
Request: filter for my bits

### ISSUE THREAD

**Issue by nathanl** [kkuchta/Vimbits#14]
It would be nice to have a filter to see the bits I've contributed, in case I want to update them.

**Comment by kkuchta** [comment]
On the todo list.  Probably just a simple profile page for each user listing the bits they's submitted, and maybe their comments.

**Comment by kkuchta** [comment]
User pages done.  They currently show the bits you've submitted; they'll probably eventually show the bits you've +1'd, and your comments.

**Comment by nathanl** [comment]
Awesome!
