### ISSUE TITLE
Feature: Tag dependent plugins and/or dependent vimbits

### ISSUE THREAD

**Issue by darcyparker** [kkuchta/Vimbits#16]
Some of the vimbits are dependent on vim plugins.  It would be nice if there was a field to collect the dependent vimplugs (perhaps using URLs to their repository?)

As well, some of the vimbits would be best broken out into reusable vimbits that other vimbits could be dependent on.  For example vimbits of functions.

And if you can see dependent vimbits, a 'where used' list would also be cool.

Example:
Potential vimbit 1
(Borrowed from http://technotales.wordpress.com/2010/03/31/preserve-a-vim-function-that-keeps-your-state/)

```
function! Preserve(command)
  " Preparation: save last search, and cursor position.
  let _s=@/
  let l = line(".")
  let c = col(".")
  " Do the business:
  execute a:command
  " Clean up: restore previous search history, and cursor position
  let @/=_s
  call cursor(l, c)
endfunction
```

Where used for vimbit 1: vimbit 2 and 3 below

Potential vimbit 2
(Depends on potential vimbit 1 above)

```
"strip all trailing white space
nnoremap <silent> <leader>ws  :call Preserve("%s/\\s\\+$//e")<CR>
```

Potential vimbit 3
(Depends on potential vimbit 1 above)

```
"reformat the indentation of the whole file
nnoremap <silent> <leader>= :call Preserve("normal gg=G")<CR>
```

**Comment by kkuchta** [comment]
An interesting idea.  It might be a bit tricky to do this elegantly from a UI perspective without cluttering up the interface.  It seems like most users so far just want useful vimrc ideas, and not complex but compartmentalized building blocks (although that's a decent idea for a site of it's own.)  Closing for now, as I don't see this happening in the next few months, anyway, but keeping it in mind for sure.
