### ISSUE TITLE
RSS Feed

### ISSUE THREAD

**Issue by jessor** [kkuchta/Vimbits#4]
for new(est) items.

**Comment by kkuchta** [comment]
Will add.  Eventually want to have a "Hot" section for people that don't want to get flooded with every new vimbit.

**Comment by bentomas** [comment]
I'm adding my vote for this!

**Comment by ghost** [comment]
+1

**Comment by kkuchta** [comment]
Done.  You can get an RSS feed for Top, New, Random, and Hot (newly introduced).
